import Head from "next/head";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import PostCard from "../components/PostCard";

export default function Home({ posts, follow }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <div className={styles.container}>
          {posts.length === 0 ? (
            <h2>No added posts</h2>
          ) : (
            <ul>
              {follow &&
                posts.map((post, i) => <PostCard post={post} key={i} />)}
            </ul>
          )}
        </div>
      </main>
    </div>
  );
}
export async function getServerSideProps(ctx) {
  // get the current environment
  let dev = process.env.NODE_ENV !== "production";
  let { DEV_URL, PROD_URL } = process.env;

  // request posts from api
  let response = await fetch(`${dev ? DEV_URL : PROD_URL}/api/posts`);
  let responseFollow = await fetch(`${dev ? DEV_URL : PROD_URL}/api/tweet`);
  // extract the data
  let data = await response.json();
  let follow = await responseFollow.json();

  return {
    props: {
      posts: data["message"],
      follow,
    },
  };
}
